export const SCRUM_BOARD_TEXT_AREA_FONT_SIZE = 14;
export const SCRUM_BOARD_TEXT_AREA_TEXT_MAX_LENGTH = 45;
export const SCRUM_BOARD_COMMENT_TEXT_AREA_FONT_SIZE = 13;
export const SCRUM_BOARD_COMMENT_TEXT_AREA_TEXT_MAX_LENGTH = 100;
